vault:
  global:
    psp:
      enable: true
    tlsDisable: false
  injector:
    enabled: true
    metrics:
      enabled: true
  server:
    auditStorage:
      enabled: true
    standalone:
      enabled: true
  csi:
    enabled: true
  ui:
    port: 8200

ingressroute:
  enabled: true
  host: "vault.example.com"