{{- if .Values.ingressroute.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: minecraft-ingressroute-tcp
spec:
  entryPoints:
    - minecraft
  routes:
    - match: HostSNI(`*`)
      services:
        - name: minecraft-minecraft
          port: {{ .Values.minecraft.minecraftServer.servicePort | default "25565" }}
{{- end }}
